version: '3.7'

services:
    front-end:
        build: ./front-end
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./front-end:/usr/src/app
        depends_on: 
            - db
            - back-end
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: hotelio
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
    back-end:
        build: ./back-end
        ports:
            - 8080:8080
        restart: always
        depends_on: 
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db/hotelio?useSSL=false
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres 